### ISSUE TITLE
contentLabel的frame问题

### ISSUE THREAD

**Issue by yunjinghui123** [JerryLMJ/LMJHorizontalScrollText#3]
contentLabel会跑出LMJHorizontalScrollTex以外

**Comment by JerryLMJ** [comment]
感谢你的提问，是滚动的字符串显示在了控件外么？可以详细的描述一下你问题么

**Comment by yunjinghui123** [comment]
滚动的字符串跑出了控件外面，而且我发现如果先设置textColor会去调用updateFrame，这个时候_contentLabel是nil
如果用约束，不先设置frame控件也是不可用的，虽然LMJHorizontalScrollText可以变化  但是里面的滚动label不会出现

**Comment by JerryLMJ** [comment]
很抱歉，最近一直在忙没能及时修复你提出的问题。
刚刚更新了代码，2.0.1版本应该已修复你所提出的问题。
我先将issue关闭，如有问题可重新打开
