### ISSUE TITLE
在tableviewcell上使用有问题 不显示任何内容

### ISSUE THREAD

**Issue by huxiaoxin** [JerryLMJ/LMJHorizontalScrollText#4]

**Comment by JerryLMJ** [comment]
我在本地做了一下测试是可以的，项目中的demo做了更新，你可以在Demo-TableViewCell中看一下我的使用。
你的问题是否是cell的重用导致的呢，能否把你的使用场景说的更详细一些？或者看一下你的代码

**Comment by huxiaoxin** [comment]
谢谢，似乎找到问题了 LMJHorizontalScrollText这个只有创建才正常显示，拿来复用好像不行，我的场景就是一个音乐列表，类似的电台列表，用户选中某个音乐（就是你文章说的通过外部的一个方法来控制每一项的文字是否做滚动动画），当前音乐文字列表在做横向滚动。似乎显示问题解决了 但是需求不对，我在你的demo里的- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath方法里调用了[text stop]方法就不显示了，您看看是不是这样

**Comment by huxiaoxin** [comment]
实际需求是一个静止的音乐列表。点一下 默认某一项就做滚动动画，在某一项滚动的过程中滑动Tableview，动画不受影响

**Comment by JerryLMJ** [comment]
根据你的问题release了一个新的版本2.0.2，你可以看一下你的问题是否解决了
我先把issue close了，如果还有问题reopen这个issue
